services:
  mongo:
    image: mongo:latest
    container_name: library-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=book
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - TZ=Asia/Jakarta
    ports:
      - "27017:27017"
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  web:
    build: .
    container_name: library-service
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongo
  initdb:
    image: node:18
    container_name: library-init-db
    depends_on:
      - mongo
      - web
    entrypoint: ["/bin/sh", "-c", "npm run init-db"]
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app